-- SolonGate schema for postgres: 44 statements.
-- Generated by apps/system/cmd/schemadump. Do not edit by hand.

CREATE TABLE solon_usage (
	user_id text PRIMARY KEY NOT NULL,
	chats_used BIGINT DEFAULT 0 NOT NULL,
	policies_used BIGINT DEFAULT 0 NOT NULL,
	updated_at BIGINT NOT NULL
);

CREATE TABLE system_settings (
	key text PRIMARY KEY NOT NULL,
	value text NOT NULL,
	description text,
	updated_by text,
	updated_at BIGINT NOT NULL
);

CREATE TABLE users (
	id text PRIMARY KEY NOT NULL,
	email text NOT NULL,
	name text,
	password_hash text,
	created_at BIGINT NOT NULL,
	updated_at BIGINT NOT NULL
);

CREATE TABLE organizations (
	id text PRIMARY KEY NOT NULL,
	name text NOT NULL,
	slug text NOT NULL,
	owner_id text NOT NULL,
	created_at BIGINT NOT NULL,
	updated_at BIGINT NOT NULL,
	FOREIGN KEY (owner_id) REFERENCES users(id) ON UPDATE no action ON DELETE cascade
);

CREATE TABLE projects (
	id text PRIMARY KEY NOT NULL,
	owner_id text NOT NULL,
	org_id text,
	name text NOT NULL,
	slug text NOT NULL,
	description text DEFAULT '',
	token_secret text NOT NULL,
	pi_enabled BIGINT DEFAULT 1,
	pi_threshold DOUBLE PRECISION DEFAULT 0.5,
	pi_mode text DEFAULT 'block',
	pi_whitelist text,
	pi_tool_config text,
	pi_custom_patterns text,
	pi_webhook_url text,
	ai_judge_enabled BIGINT DEFAULT 0,
	ai_judge_model text DEFAULT 'llama-3.1-8b-instant',
	ai_judge_endpoint text DEFAULT 'https://api.groq.com/openai',
	ai_judge_timeout_ms BIGINT DEFAULT 5000,
	created_at BIGINT NOT NULL,
	updated_at BIGINT NOT NULL,
	FOREIGN KEY (owner_id) REFERENCES users(id) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (org_id) REFERENCES organizations(id) ON UPDATE no action ON DELETE set null
);

CREATE TABLE tools (
	id text PRIMARY KEY NOT NULL,
	project_id text NOT NULL,
	name text NOT NULL,
	description text DEFAULT '',
	input_schema text,
	permissions text DEFAULT '["READ"]',
	enabled BIGINT DEFAULT 1 NOT NULL,
	created_at BIGINT NOT NULL,
	updated_at BIGINT NOT NULL,
	FOREIGN KEY (project_id) REFERENCES projects(id) ON UPDATE no action ON DELETE cascade
);

CREATE TABLE used_nonces (
	nonce text PRIMARY KEY NOT NULL,
	project_id text NOT NULL,
	used_at BIGINT NOT NULL,
	FOREIGN KEY (project_id) REFERENCES projects(id) ON UPDATE no action ON DELETE cascade
);

CREATE TABLE api_keys (
	id text PRIMARY KEY NOT NULL,
	project_id text NOT NULL,
	key_prefix text NOT NULL,
	key_hash text NOT NULL,
	name text NOT NULL,
	is_live BIGINT DEFAULT 0 NOT NULL,
	user_id text,
	last_used_at BIGINT,
	revoked_at BIGINT,
	created_at BIGINT NOT NULL,
	FOREIGN KEY (project_id) REFERENCES projects(id) ON UPDATE no action ON DELETE cascade
);

CREATE TABLE audit_logs (
	id text PRIMARY KEY NOT NULL,
	project_id text NOT NULL,
	request_id text NOT NULL,
	session_id text,
	tool_name text NOT NULL,
	server_name text,
	permission text NOT NULL,
	trust_level text NOT NULL,
	decision text NOT NULL,
	matched_rule_id text,
	reason text,
	evaluation_time_ms DOUBLE PRECISION,
	arguments_hash text,
	arguments_summary text,
	pi_detected BIGINT,
	pi_trust_score DOUBLE PRECISION,
	pi_blocked BIGINT,
	pi_categories text,
	pi_stage_scores text,
	agent_id text,
	agent_name text,
	sub_agent_id text,
	sub_agent_name text,
	api_key_id text,
	created_at BIGINT NOT NULL,
	FOREIGN KEY (project_id) REFERENCES projects(id) ON UPDATE no action ON DELETE cascade
);

CREATE TABLE mcp_servers (
	id text PRIMARY KEY NOT NULL,
	project_id text NOT NULL,
	name text NOT NULL,
	url text NOT NULL,
	status text DEFAULT 'inactive' NOT NULL,
	command text,
	args text,
	created_at BIGINT NOT NULL,
	updated_at BIGINT NOT NULL,
	FOREIGN KEY (project_id) REFERENCES projects(id) ON UPDATE no action ON DELETE cascade
);

CREATE TABLE org_members (
	id text PRIMARY KEY NOT NULL,
	org_id text NOT NULL,
	user_id text NOT NULL,
	role text DEFAULT 'member' NOT NULL,
	created_at BIGINT NOT NULL,
	updated_at BIGINT NOT NULL,
	FOREIGN KEY (org_id) REFERENCES organizations(id) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE no action ON DELETE cascade
);

CREATE TABLE policy_versions (
	id text PRIMARY KEY NOT NULL,
	project_id text NOT NULL,
	version BIGINT NOT NULL,
	policy_data text NOT NULL,
	hash text NOT NULL,
	reason text,
	created_by text,
	rego_source text,
	wasm_bundle text,
	variant_artifacts text,
	created_at BIGINT NOT NULL,
	FOREIGN KEY (project_id) REFERENCES projects(id) ON UPDATE no action ON DELETE cascade
);

CREATE INDEX IF NOT EXISTS api_keys_key_prefix_idx ON api_keys (key_prefix);

CREATE INDEX IF NOT EXISTS api_keys_project_id_idx ON api_keys (project_id);

CREATE INDEX IF NOT EXISTS api_keys_project_name_idx ON api_keys (project_id,name);

CREATE INDEX IF NOT EXISTS audit_logs_project_id_created_at_idx ON audit_logs (project_id,created_at);

CREATE INDEX IF NOT EXISTS audit_logs_agent_id_idx ON audit_logs (agent_id);

CREATE INDEX IF NOT EXISTS audit_logs_session_id_idx ON audit_logs (project_id,session_id);

CREATE INDEX IF NOT EXISTS mcp_servers_project_id_idx ON mcp_servers (project_id);

CREATE UNIQUE INDEX IF NOT EXISTS org_members_org_user_unique ON org_members (org_id,user_id);

CREATE INDEX IF NOT EXISTS org_members_org_id_idx ON org_members (org_id);

CREATE INDEX IF NOT EXISTS org_members_user_id_idx ON org_members (user_id);

CREATE UNIQUE INDEX IF NOT EXISTS organizations_slug_unique ON organizations (slug);

CREATE INDEX IF NOT EXISTS organizations_owner_id_idx ON organizations (owner_id);

CREATE INDEX IF NOT EXISTS policy_versions_project_id_version_idx ON policy_versions (project_id,version);

CREATE UNIQUE INDEX IF NOT EXISTS projects_slug_unique ON projects (slug);

CREATE INDEX IF NOT EXISTS projects_owner_id_idx ON projects (owner_id);

CREATE INDEX IF NOT EXISTS projects_org_id_idx ON projects (org_id);

CREATE INDEX IF NOT EXISTS tools_project_id_idx ON tools (project_id);

CREATE INDEX IF NOT EXISTS used_nonces_project_id_idx ON used_nonces (project_id);

CREATE UNIQUE INDEX IF NOT EXISTS users_email_unique ON users (email);

ALTER TABLE policy_versions ADD COLUMN IF NOT EXISTS rego_source TEXT;

ALTER TABLE policy_versions ADD COLUMN IF NOT EXISTS wasm_bundle TEXT;

CREATE INDEX IF NOT EXISTS audit_logs_session_id_idx ON audit_logs (project_id, session_id);

CREATE INDEX IF NOT EXISTS audit_logs_project_decision_idx ON audit_logs (project_id, decision);

CREATE INDEX IF NOT EXISTS audit_logs_project_created_agent_idx ON audit_logs (project_id, created_at, agent_name);

CREATE TABLE IF NOT EXISTS token_usage (
      id TEXT PRIMARY KEY,
      project_id TEXT NOT NULL,
      api_key_id TEXT,
      user_id TEXT,
      session_id TEXT,
      agent_id TEXT,
      agent_name TEXT,
      source TEXT,
      measure TEXT NOT NULL DEFAULT 'billed',
      input_tokens BIGINT NOT NULL DEFAULT 0,
      output_tokens BIGINT NOT NULL DEFAULT 0,
      cache_read_tokens BIGINT NOT NULL DEFAULT 0,
      cache_write_tokens BIGINT NOT NULL DEFAULT 0,
      reasoning_tokens BIGINT NOT NULL DEFAULT 0,
      total_tokens BIGINT NOT NULL DEFAULT 0,
      created_at BIGINT NOT NULL
    );

CREATE INDEX IF NOT EXISTS token_usage_project_created_idx ON token_usage (project_id, created_at);

CREATE INDEX IF NOT EXISTS token_usage_project_key_created_idx ON token_usage (project_id, api_key_id, created_at);

CREATE INDEX IF NOT EXISTS token_usage_session_idx ON token_usage (session_id, created_at);

ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS session_id TEXT;

ALTER TABLE api_keys ADD COLUMN IF NOT EXISTS user_id TEXT;

CREATE INDEX IF NOT EXISTS api_keys_project_name_idx ON api_keys (project_id, name);

CREATE UNIQUE INDEX IF NOT EXISTS org_members_org_user_unique ON org_members (org_id, user_id);

