// schemadump prints the COMPLETE schema for a dialect: the base tables and the
// ones the API creates at runtime, in an order the database will accept.
//
// It exists because a DBA applies the schema, a security review reads it, and a
// hardened installation does not give the application CREATE rights at all — so
// "start it and see what it makes" is not an answer. With this the file they
// apply is complete, and EnsureRuntimeTables then finds everything already there
// and does nothing, which is the same code path either way.
//
//	go run ./cmd/schemadump -dialect postgres > schema.sql
//	go run ./cmd/schemadump -dialect postgres -runtime-only > runtime.sql
package main

import (
	"bufio"
	"flag"
	"fmt"
	"os"
	"strings"

	"github.com/codeyevsky/solongate/system/internal/store"
)

func main() {
	dialect := flag.String("dialect", "postgres", "postgres or sqlite")
	runtimeOnly := flag.Bool("runtime-only", false, "omit the base tables")
	flag.Parse()

	var d store.Dialect
	switch strings.ToLower(*dialect) {
	case "postgres", "postgresql", "pg":
		d = store.Postgres
	case "sqlite", "sqlite3":
		d = store.SQLite
	default:
		fmt.Fprintf(os.Stderr, "schemadump: unknown dialect %q\n", *dialect)
		os.Exit(2)
	}

	w := bufio.NewWriter(os.Stdout)
	defer w.Flush()

	var stmts []string
	if *runtimeOnly {
		// Upgrading a database that already exists: every ALTER has work to do,
		// because on an old database the column really is absent.
		stmts = store.RuntimeDDL(d)
	} else {
		base, err := store.BaseDDL(d)
		if err != nil {
			fmt.Fprintf(os.Stderr, "schemadump: %v\n", err)
			os.Exit(1)
		}
		// Creating from scratch: an ALTER whose column the base schema already
		// declares must NOT be emitted. SQLite has no ADD COLUMN IF NOT EXISTS, so
		// it is an error there — and a file that errors is a file a DBA cannot tell
		// has applied. Worse, applied by anything that stops on error, it aborted at
		// the first one and left the schema incomplete.
		runtime, err := store.RuntimeDDLFor(d, base)
		if err != nil {
			fmt.Fprintf(os.Stderr, "schemadump: %v\n", err)
			os.Exit(1)
		}
		stmts = append(append(stmts, base...), runtime...)
	}

	fmt.Fprintf(w, "-- SolonGate schema for %s: %d statements.\n", *dialect, len(stmts))
	fmt.Fprintf(w, "-- Generated by apps/system/cmd/schemadump. Do not edit by hand.\n\n")
	for _, s := range stmts {
		fmt.Fprintf(w, "%s;\n\n", strings.TrimSpace(s))
	}
}
