// SPDX-License-Identifier: Apache-2.0

// THIS IS THE LAUNCHER. Edit it here.
//
// It was generated from packages/proxy/src/hook-launcher.ts by
// scripts/gen-launcher.mjs, because a TypeScript installer wrote the same
// launcher script and whichever ran last won. A byte of difference would have
// had each rewriting the other's copy on every install, with the two node
// search orders drifting apart unnoticed.
//
// That installer is gone, and so is the generator. One program writes this file
// now, which is the only reason it is safe to edit by hand.

package install

import (
	"path/filepath"
	"strings"
)

// launcherScript is the launcher with the install-time node baked in. See
// launcher.go for what it is for and why it is not a node path in the config.
func launcherScript(pinnedNode string) string {
	pinned := strings.ReplaceAll(filepath.ToSlash(pinnedNode), `'`, `'\''`)
	return `#!/bin/sh
# SolonGate hook launcher — generated by ` +
		"`" +
		`solongate init --global` +
		"`" +
		` / ` +
		"`" +
		`repair` +
		"`" +
		`.
#
# Finds a working node and execs the hook with it. Do not edit: a reinstall
# overwrites this file, and on macOS it is chflags-locked besides.
#
# The reason it exists rather than the hook naming a node directly: an absolute
# node path recorded at install time is a Homebrew Cellar path or an nvm version
# directory, and both are deleted by a routine upgrade. The hook then could not
# start, nothing was enforced, nothing was logged, and every check still said
# the guard was registered — because it was.

set -u

script="${1:-}"
[ -n "$script" ] || { echo "solongate: launcher called with no hook script" >&2; exit 1; }
shift

hook=${script##*/}
home=${HOME:-~}
beatdir="$home/.solongate/.beat"

# The beat. Written BEFORE node is resolved, because its whole job is to record
# that the client invoked us — which is true even when everything after this
# line fails. The file's modification time is the timestamp; nothing is forked
# to produce one, and the directory test is a builtin.
#
# The braces matter. A redirect into a missing directory is reported by the
# SHELL, before the command runs, so a ` +
		"`" +
		`2>/dev/null` +
		"`" +
		` on the printf alone does
# not suppress it — it lands on the hook's stderr, and Claude Code shows a
# hook's stderr to the person using it. Redirecting the group catches both.
beat() {
  [ -d "$beatdir" ] || mkdir -p "$beatdir" 2>/dev/null || return 0
  { printf '%s\n' "$1" > "$beatdir/$hook"; } 2>/dev/null || true
}

try() {
  [ -n "${1:-}" ] && [ -x "$1" ]
}

resolve_node() {
  # Told explicitly.
  if try "${SOLONGATE_NODE:-}"; then echo "$SOLONGATE_NODE"; return 0; fi
  # The node this was installed with.
  if try '` +
		pinned +
		`'; then echo '` +
		pinned +
		`'; return 0; fi
  # PATH, when the client gave us one worth having.
  p=$(command -v node 2>/dev/null) || p=
  if try "$p"; then echo "$p"; return 0; fi
  # The fixed locations.
  for c in "/opt/homebrew/bin/node" "/usr/local/bin/node" "/opt/homebrew/opt/node/bin/node" "/usr/local/opt/node/bin/node" "/usr/bin/node" "/usr/local/n/versions/node/*/bin/node" "/snap/bin/node"; do
    for g in $c; do
      if try "$g"; then echo "$g"; return 0; fi
    done
  done
  # The version managers.
  for c in "${NVM_DIR:-}"/versions/node/*/bin/node "$home"/.nvm/versions/node/*/bin/node "$home"/.local/share/fnm/node-versions/*/installation/bin/node "$home"/Library/Application Support/fnm/node-versions/*/installation/bin/node "$home"/.volta/tools/image/node/*/bin/node "$home"/.asdf/installs/nodejs/*/bin/node "$home"/.asdf/installs/node/*/bin/node; do
    for g in $c; do
      if try "$g"; then echo "$g"; return 0; fi
    done
  done
  return 1
}

node_bin=$(resolve_node) || node_bin=

# --sg-doctor: report what would be used and leave. This is what ` +
		"`" +
		`solongate
# doctor` +
		"`" +
		` runs, so the health check exercises the REAL resolution rather than a
# copy of it that can drift.
if [ "$script" = "--sg-doctor" ] || [ "${1:-}" = "--sg-doctor" ]; then
  [ -n "$node_bin" ] && { echo "$node_bin"; exit 0; }
  echo "no node found" >&2
  exit 1
fi

if [ -z "$node_bin" ]; then
  beat "no-node"
  # Nothing can be enforced without node, and which way to fail is not a
  # judgement call: the guard is fail-closed, so it refuses the call and says
  # why. Everything else here only records what already happened, and refusing
  # a tool call because the log could not be written would be a worse product
  # than a gap in the log.
  echo "solongate: no node runtime found, so $hook did not run." >&2
  echo "solongate: run \` +
		"`" +
		`solongate repair\` +
		"`" +
		` in a terminal, or set SOLONGATE_NODE to your node binary." >&2
  case "$hook" in
    guard.mjs) echo "solongate: this tool call is REFUSED — the guard is fail-closed." >&2; exit 2 ;;
    *) exit 0 ;;
  esac
fi

beat "$node_bin"
exec "$node_bin" "$script" "$@"
`
}
