package store_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/codeyevsky/solongate/system/internal/store"
)

// The checked-in schema files are what this package generates, byte for byte.
//
// They are checked in because a DBA applies them and a review reads them, and
// generated because writing them by hand is how they stop matching the product.
// Both of those are only true while the file on disk is the file the generator
// produces — a schema that has drifted is worse than no schema, because it looks
// authoritative.
//
// It fails with the command to fix it rather than with a diff, because the fix is
// always the same and never "edit the file".
func TestCheckedInSchemaFilesMatchTheGenerator(t *testing.T) {
	for _, tc := range []struct {
		file    string
		dialect store.Dialect
		name    string
	}{
		{"sqlite.sql", store.SQLite, "sqlite"},
		{"postgres.sql", store.Postgres, "postgres"},
	} {
		path := filepath.Join("..", "..", "..", "..", "tools", "schema", tc.file)
		onDisk, err := os.ReadFile(path)
		if err != nil {
			// SKIPPED, NOT FAILED, when the file is not there.
			//
			// It lives outside this module, and the module is built on its own
			// in the release image — which copies apps/system and its sibling
			// packages and no tools/ at all. Failing there turns `go test` in
			// the Dockerfile into a failure about a file the image was never
			// meant to carry. The guarantee is kept where it is checkable: a
			// repository checkout, which is what a developer and CI both run.
			t.Skipf("tools/schema/%s is not beside this module; nothing to compare", tc.file)
			continue
		}

		base, err := store.BaseDDL(tc.dialect)
		if err != nil {
			t.Fatalf("BaseDDL(%s): %v", tc.name, err)
		}
		stmts := append(base, store.RuntimeDDL(tc.dialect)...)

		var b strings.Builder
		b.WriteString("-- SolonGate schema for " + tc.name + ": ")
		b.WriteString(itoa(len(stmts)))
		b.WriteString(" statements.\n")
		b.WriteString("-- Generated by apps/system/cmd/schemadump. Do not edit by hand.\n\n")
		for _, s := range stmts {
			b.WriteString(strings.TrimSpace(s))
			b.WriteString(";\n\n")
		}

		if string(onDisk) != b.String() {
			t.Errorf("tools/schema/%s has drifted from the generator. Regenerate it:\n"+
				"  cd apps/system && go run ./cmd/schemadump -dialect %s > ../../tools/schema/%s",
				tc.file, tc.name, tc.file)
		}
	}
}

// itoa keeps this test off strconv, so the expected header is assembled the same
// way in one place and cannot disagree with itself.
func itoa(n int) string {
	if n == 0 {
		return "0"
	}
	var digits []byte
	for n > 0 {
		digits = append([]byte{byte('0' + n%10)}, digits...)
		n /= 10
	}
	return string(digits)
}
