package store_test

import (
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"github.com/codeyevsky/solongate/system/internal/store"
)

// The checked-in schema files are what this package generates, byte for byte.
//
// They are checked in because a DBA applies them and a review reads them, and
// generated because writing them by hand is how they stop matching the product.
// Both of those are only true while the file on disk is the file the generator
// produces — a schema that has drifted is worse than no schema, because it looks
// authoritative.
//
// It fails with the command to fix it rather than with a diff, because the fix is
// always the same and never "edit the file".
func TestCheckedInSchemaFilesMatchTheGenerator(t *testing.T) {
	for _, tc := range []struct {
		file    string
		dialect store.Dialect
		name    string
	}{
		{"sqlite.sql", store.SQLite, "sqlite"},
		{"postgres.sql", store.Postgres, "postgres"},
	} {
		path := filepath.Join("..", "..", "..", "..", "tools", "schema", tc.file)
		onDisk, err := os.ReadFile(path)
		if err != nil {
			// SKIPPED, NOT FAILED, when the file is not there.
			//
			// It lives outside this module, and the module is built on its own
			// in the release image — which copies apps/system and its sibling
			// packages and no tools/ at all. Failing there turns `go test` in
			// the Dockerfile into a failure about a file the image was never
			// meant to carry. The guarantee is kept where it is checkable: a
			// repository checkout, which is what a developer and CI both run.
			t.Skipf("tools/schema/%s is not beside this module; nothing to compare", tc.file)
			continue
		}

		base, err := store.BaseDDL(tc.dialect)
		if err != nil {
			t.Fatalf("BaseDDL(%s): %v", tc.name, err)
		}
		runtime, err := store.RuntimeDDLFor(tc.dialect, base)
		if err != nil {
			t.Fatalf("RuntimeDDLFor(%s): %v", tc.name, err)
		}
		stmts := append(base, runtime...)

		var b strings.Builder
		b.WriteString("-- SolonGate schema for " + tc.name + ": ")
		b.WriteString(itoa(len(stmts)))
		b.WriteString(" statements.\n")
		b.WriteString("-- Generated by apps/system/cmd/schemadump. Do not edit by hand.\n\n")
		for _, s := range stmts {
			b.WriteString(strings.TrimSpace(s))
			b.WriteString(";\n\n")
		}

		if string(onDisk) != b.String() {
			t.Errorf("tools/schema/%s has drifted from the generator. Regenerate it:\n"+
				"  cd apps/system && go run ./cmd/schemadump -dialect %s > ../../tools/schema/%s",
				tc.file, tc.name, tc.file)
		}
	}
}

// itoa keeps this test off strconv, so the expected header is assembled the same
// way in one place and cannot disagree with itself.
func itoa(n int) string {
	if n == 0 {
		return "0"
	}
	var digits []byte
	for n > 0 {
		digits = append([]byte{byte('0' + n%10)}, digits...)
		n /= 10
	}
	return string(digits)
}

// A from-scratch dump must not carry an ALTER for a column the base schema
// already has.
//
// SQLite cannot say ADD COLUMN IF NOT EXISTS, so each of those was an error
// against a database built from this same file — four of them. That is worse than
// noise in a file whose entire purpose is to be applied by a DBA: run through
// anything that stops on error (psql -v ON_ERROR_STOP=1, sqlite3 -bail, most
// migration tools) the file aborted at the FIRST one and left the database missing
// a table and six indexes, reporting a duplicate-column error that pointed nowhere
// near it.
//
// Checked by PARSING the dump rather than by applying it, so the guarantee holds
// on a machine with no database of either kind — the drift test above is already
// the thing that keeps the checked-in files honest.
func TestAFromScratchDumpAddsNoColumnTheBaseAlreadyHas(t *testing.T) {
	for _, tc := range []struct {
		dialect store.Dialect
		name    string
	}{
		{store.SQLite, "sqlite"},
		{store.Postgres, "postgres"},
	} {
		base, err := store.BaseDDL(tc.dialect)
		if err != nil {
			t.Fatalf("BaseDDL(%s): %v", tc.name, err)
		}
		runtime, err := store.RuntimeDDLFor(tc.dialect, base)
		if err != nil {
			t.Fatalf("RuntimeDDLFor(%s): %v", tc.name, err)
		}

		// What the base schema declares, read back out of the rendered text so
		// this test does not trust the same list the code under test used.
		declared := map[string]bool{}
		for _, stmt := range base {
			m := regexp.MustCompile(`(?is)^\s*CREATE TABLE\s+(?:IF NOT EXISTS\s+)?[\x60"]?(\w+)`).FindStringSubmatch(stmt)
			if m == nil {
				continue
			}
			table := strings.ToLower(m[1])
			for _, col := range regexp.MustCompile("(?m)^\\s*[\x60\"]?(\\w+)[\x60\"]?\\s+(?i:text|integer|bigint|real|double|boolean|timestamp)").FindAllStringSubmatch(stmt, -1) {
				declared[table+"."+strings.ToLower(col[1])] = true
			}
		}
		if len(declared) == 0 {
			t.Fatalf("%s: parsed no columns out of the base schema, so this test proves nothing", tc.name)
		}

		addCol := regexp.MustCompile(`(?i)^ALTER TABLE\s+(?:IF EXISTS\s+)?[\x60"]?(\w+)[\x60"]?\s+ADD COLUMN\s+(?:IF NOT EXISTS\s+)?[\x60"]?(\w+)`)
		for _, stmt := range runtime {
			m := addCol.FindStringSubmatch(strings.TrimSpace(stmt))
			if m == nil {
				continue
			}
			key := strings.ToLower(m[1]) + "." + strings.ToLower(m[2])
			if declared[key] {
				t.Errorf("%s: dump adds %s, which the base schema already declares —\n"+
					"  on sqlite that is a duplicate-column error, and a tool that stops on error\n"+
					"  abandons the rest of the file", tc.name, key)
			}
		}
	}
}
