//go:build ignore

// The generator behind bundles_gen.go.
//
//	go run generate.go
//
// It is the Go half of apps/api/scripts/embed-hook.mjs and reads the SAME three
// files that script reads — packages/proxy/hooks — rather than transcribing the
// TypeScript it produces. Two implementations copying each other's numbers is
// how a version and a checksum end up describing different bytes, and a bundle
// whose checksum does not verify is refused silently by every installed hook.
//
// Regenerate after `pnpm --filter @solongate/proxy build:hooks`, in the same
// commit. A stale bundle here is not a build failure; it is a fleet that stops
// updating.
package main

import (
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
)

// The hooks, in embed-hook.mjs's order. The guard is served from
// guard.bundled.mjs and not guard.mjs: the bundled file is the one with its
// imports inlined, and it is what a machine can actually run.
var hooks = []struct{ name, file string }{
	{"guard", "guard.bundled.mjs"},
	{"audit", "audit.mjs"},
	{"shield", "shield.mjs"},
	// The token reader is served for the same reason as the other three. It is
	// the surviving half of what used to be the conversation hook: until it was
	// here the only way a machine got an updated reader was a full reinstall, so
	// a fleet that had simply updated reported no spend at all — which is
	// indistinguishable from a fleet that spends nothing.
	{"tokens", "tokens.mjs"},
}

// hookVersionRe is the expression the hook, the CLI and embed-hook.mjs all use.
// The version lives in the source file because the file is the unit that ships.
var hookVersionRe = regexp.MustCompile(`HOOK_VERSION\s*=\s*(\d+)`)

func main() {
	hooksDir := filepath.Join("..", "..", "..", "..", "packages", "proxy", "hooks")

	out := &bytesBuffer{}
	out.printf("// Code generated by generate.go. DO NOT EDIT.\n")
	out.printf("// Source: packages/proxy/hooks — regenerate with `go run generate.go`.\n\n")
	out.printf("package hookbundle\n\n")
	out.printf("var bundles = map[string]Bundle{\n")

	for _, h := range hooks {
		path := filepath.Join(hooksDir, h.file)
		raw, err := os.ReadFile(path)
		if err != nil {
			log.Fatalf("hookbundle: %v", err)
		}

		// The digest is over the FILE's bytes, not over the base64. That is what
		// the installed hook checks: it decodes first and hashes the result.
		sum := sha256.Sum256(raw)

		m := hookVersionRe.FindSubmatch(raw)
		if m == nil {
			log.Fatalf("hookbundle: %s has no HOOK_VERSION; serving it as version 0 would tell every guard it is older than what they run", h.file)
		}
		version, err := strconv.ParseInt(string(m[1]), 10, 64)
		if err != nil {
			log.Fatalf("hookbundle: %s has an unreadable HOOK_VERSION: %v", h.file, err)
		}

		out.printf("\t%q: {\n", h.name)
		out.printf("\t\tVersion: %d,\n", version)
		out.printf("\t\tSHA256:  %q,\n", hex.EncodeToString(sum[:]))
		out.printf("\t\tContent: %q,\n", base64.StdEncoding.EncodeToString(raw))
		out.printf("\t},\n")

		log.Printf("hookbundle: %s version=%d sha=%s bytes=%d",
			h.file, version, hex.EncodeToString(sum[:])[:12], len(raw))
	}

	out.printf("}\n")

	formatted, err := format.Source(out.b)
	if err != nil {
		log.Fatalf("hookbundle: generated source does not parse: %v", err)
	}
	if err := os.WriteFile("bundles_gen.go", formatted, 0o644); err != nil {
		log.Fatalf("hookbundle: %v", err)
	}
}

type bytesBuffer struct{ b []byte }

func (w *bytesBuffer) printf(f string, a ...any) { w.b = append(w.b, fmt.Sprintf(f, a...)...) }
